-- +goose Up
CREATE TABLE users(id UUID UNIQUE PRIMARY KEY NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at TIMESTAMP NOT NULL, email TEXT NOT NULL UNIQUE);
-- +goose Down
DROP TABLE users;
