-- +goose Up
CREATE TABLE chirps(id UUID PRIMARY KEY NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL, body TEXT NOT NULL, user_id UUID NOT NULL , CONSTRAINT fk_user_id FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE cascade );
-- +goose Down
DROP TABLE chirps;
